version: '3.8'

services:
  # Base de Datos MySQL
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sistema_compras
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  # Aplicación Backend
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sistema_compras
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  # Aplicación Frontend
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend